# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""FlyDSL-backed FP8 rowwise preshuffle GEMM.

Phase A (enablement) of the WP-G3 migration: wrap the FlyDSL
``kernels/preshuffle_gemm.py`` kernel behind the existing MSLK op names
``f8f8bf16_rowwise_preshuffle`` / ``f8f8f16_rowwise_preshuffle`` so it is a
drop-in replacement for the CK (``DeviceGemmMultiD_Xdl_CShuffle_V3_BPreshuffle``)
implementation.

Contract (identical to the CK op, see csrc/gemm/gemm_ops.cpp and
bench/gemm/gemm_ops.py):

    out = f8f8{bf16,f16}_rowwise_preshuffle(XQ, WQ, x_scale, w_scale,
                                            bias=None, use_fast_accum=True)

    XQ        : (M, K)   float8_e4m3 (fnuz on gfx942, fn on gfx950)
    WQ        : (N, K)   float8, ALREADY preshuffled by mslk.quantize.shuffle.ck_preshuffle(w, 16)
    x_scale   : (M,)     float32, per-row scale of A
    w_scale   : (N,)     float32, per-row scale of B
    bias      : unsupported on AMD (must be None)
    returns   : (M, N)   bf16 or f16

The FlyDSL in-kernel B layout has been verified byte-identical to CK's
ck_preshuffle (host shuffle round-trips; GEMM matches the torch dequant
reference for both bf16 and fp16 out on gfx942).
"""

import functools
from typing import Optional, Tuple

import torch


# Import the FlyDSL kernel builder + arch probe once, only when first needed.
# FlyDSL is a runtime dependency of MSLK; the kernel template ships as the
# `kernels.preshuffle_gemm` module (see FlyDSL packaging).
#
# REBASE POINT: the FlyDSL kernel namespace is not finalized. When the FlyDSL
# integration PR lands in MSLK, update this single import to match wherever the
# kernels end up (e.g. `flydsl.kernels.preshuffle_gemm` or
# `mslk.gemm.flydsl.kernels.preshuffle_gemm`). This is the only line that needs
# to change.
@functools.lru_cache(maxsize=1)
def _kernel_api():
    from kernels.preshuffle_gemm import compile_preshuffle_gemm_a8
    from flydsl.runtime.device import get_rocm_arch

    return compile_preshuffle_gemm_a8, str(get_rocm_arch())


# Cache compiled JitFunctions keyed by (M, N, K, out_dtype, config).
_COMPILE_CACHE: dict = {}


# Kernel config: (tile_m, tile_n, tile_k, lds_stage, use_async_copy).
Config = Tuple[int, int, int, int, bool]

# Autotuned shape -> best config table (Phase B / WP-G3).
# Generated by bench/gemm/autotune_preshuffle.py on gfx942 (fp8_e4m3fnuz),
# llama3_70b shape set. Regenerate + extend for new arch/shapes.
_TUNED: dict = {
    (1, 1280, 8192): (16, 64, 512, 1, False),
    (1, 8192, 1024): (16, 64, 256, 1, True),
    (1, 7168, 8192): (16, 64, 512, 2, False),
    (1, 8192, 3584): (16, 64, 512, 2, False),
    (16, 1280, 8192): (16, 64, 512, 1, False),
    (16, 8192, 1024): (16, 128, 256, 1, True),
    (16, 7168, 8192): (16, 64, 512, 1, True),
    (16, 8192, 3584): (16, 64, 512, 2, False),
    (32, 1280, 8192): (16, 64, 512, 1, False),
    (32, 8192, 1024): (32, 64, 512, 1, True),
    (32, 7168, 8192): (32, 64, 512, 2, False),
    (32, 8192, 3584): (32, 64, 512, 1, True),
    (64, 1280, 8192): (32, 64, 512, 1, True),
    (64, 8192, 1024): (64, 64, 256, 1, True),
    (64, 7168, 8192): (64, 64, 512, 1, True),
    (64, 8192, 3584): (64, 64, 512, 2, False),
    (96, 1280, 8192): (32, 64, 512, 1, True),
    (96, 8192, 1024): (64, 64, 256, 1, True),
    (96, 7168, 8192): (64, 64, 512, 1, False),
    (96, 8192, 3584): (64, 64, 512, 1, False),
    (128, 1280, 8192): (32, 64, 512, 1, True),
    (128, 8192, 1024): (64, 64, 256, 1, True),
    (128, 7168, 8192): (64, 64, 512, 1, False),
    (128, 8192, 3584): (64, 64, 512, 1, False),
}


def _fallback_config(M: int, N: int, K: int) -> Config:
    """Constraint-safe config for shapes not in the tuned table.

    Mirrors the structure the autotuner consistently found best for this op:
    small tile_n (skinny GEMMs), largest valid tile_k, tile_m tracking M
    (capped at 64 to stay within the 64KB LDS limit), lds_stage=1.

    Constraints (fp8): tile_k%64==0, (tile_m*tile_k)%4096==0,
    (tile_n*tile_k)%4096==0, K%tile_k==0, N%tile_n==0.
    """
    tile_m = 16 if M <= 16 else 32 if M <= 32 else 64
    tile_k = next((tk for tk in (512, 256, 128, 64)
                   if K % tk == 0 and (tile_m * tk) % 4096 == 0), None)
    if tile_k is None:
        raise ValueError(f"No valid tile_k for K={K} (must be a multiple of 64 dividing K).")
    tile_n = next((tn for tn in (64, 128, 256)
                   if N % tn == 0 and (tn * tile_k) % 4096 == 0), None)
    if tile_n is None:
        raise ValueError(f"No valid tile_n for N={N}, tile_k={tile_k}.")
    return (tile_m, tile_n, tile_k, 1, False)


# Pick the kernel config for a shape: tuned table if present, else fallback.
def _select_config(M: int, N: int, K: int) -> Config:
    cfg = _TUNED.get((M, N, K))
    return cfg if cfg is not None else _fallback_config(M, N, K)


# Compile (or reuse a cached) FlyDSL JitFunction for this shape/dtype/config.
def _get_launch_fn(M, N, K, out_dtype, cfg: Config):
    key = (M, N, K, out_dtype, cfg)
    fn = _COMPILE_CACHE.get(key)
    if fn is None:
        compile_preshuffle_gemm_a8, _arch = _kernel_api()
        tile_m, tile_n, tile_k, lds_stage, use_async_copy = cfg
        fn = compile_preshuffle_gemm_a8(
            M=M, N=N, K=K,
            tile_m=tile_m, tile_n=tile_n, tile_k=tile_k,
            in_dtype="fp8", out_dtype=out_dtype,
            lds_stage=lds_stage, use_async_copy=use_async_copy,
        )
        _COMPILE_CACHE[key] = fn
    return fn


# Reinterpret an fp8 tensor as raw int8 bytes for passing to the kernel.
def _as_i8(t: torch.Tensor) -> torch.Tensor:
    return t.view(torch.int8) if "float8" in str(t.dtype) else t


# Core adapter: marshal MSLK inputs, run the FlyDSL kernel, return (M, N) output.
def _rowwise_preshuffle_impl(
    XQ: torch.Tensor,
    WQ: torch.Tensor,
    x_scale: torch.Tensor,
    w_scale: torch.Tensor,
    out_dtype: str,
    bias: Optional[torch.Tensor] = None,
    use_fast_accum: bool = True,
) -> torch.Tensor:
    if bias is not None:
        raise NotImplementedError("AMD preshuffle GEMM does not support fused bias.")
    if not use_fast_accum:
        raise NotImplementedError("AMD does not support disabling use_fast_accum.")
    if out_dtype not in ("bf16", "fp16"):
        raise ValueError(f"out_dtype must be 'bf16' or 'fp16', got {out_dtype!r}")

    assert XQ.is_cuda and WQ.is_cuda, "inputs must be on device"
    torch_out_dtype = torch.bfloat16 if out_dtype == "bf16" else torch.float16

    # XQ may carry leading dims (…, K); flatten to (M, K).
    *lead, K = XQ.shape
    M = 1
    for d in lead:
        M *= d
    XQ2 = XQ.reshape(M, K)
    N = WQ.shape[0]
    assert WQ.shape[1] == K, f"WQ K-dim {WQ.shape[1]} != XQ K-dim {K}"

    if M == 0 or N == 0 or K == 0:
        out = XQ.new_zeros((*lead, N), dtype=torch_out_dtype)
        return out

    cfg = _select_config(M, N, K)
    launch_fn = _get_launch_fn(M, N, K, out_dtype, cfg)

    c_out = torch.zeros((M, N), dtype=torch_out_dtype, device=XQ.device)
    launch_fn(
        c_out.view(-1),
        _as_i8(XQ2.contiguous().view(-1)),
        _as_i8(WQ.contiguous().view(-1)),
        x_scale.contiguous().view(-1),
        w_scale.contiguous().view(-1),
        M, N, torch.cuda.current_stream(),
    )
    return c_out.reshape(*lead, N)


# Public op: FP8 rowwise preshuffle GEMM with bf16 output.
def f8f8bf16_rowwise_preshuffle(
    XQ: torch.Tensor,
    WQ: torch.Tensor,
    x_scale: torch.Tensor,
    w_scale: torch.Tensor,
    bias: Optional[torch.Tensor] = None,
    use_fast_accum: bool = True,
) -> torch.Tensor:
    """FP8 rowwise preshuffle GEMM, bf16 output (FlyDSL backend)."""
    return _rowwise_preshuffle_impl(
        XQ, WQ, x_scale, w_scale, "bf16", bias=bias, use_fast_accum=use_fast_accum
    )


# Public op: FP8 rowwise preshuffle GEMM with fp16 output.
def f8f8f16_rowwise_preshuffle(
    XQ: torch.Tensor,
    WQ: torch.Tensor,
    x_scale: torch.Tensor,
    w_scale: torch.Tensor,
    bias: Optional[torch.Tensor] = None,
    use_fast_accum: bool = True,
) -> torch.Tensor:
    """FP8 rowwise preshuffle GEMM, fp16 output (FlyDSL backend)."""
    return _rowwise_preshuffle_impl(
        XQ, WQ, x_scale, w_scale, "fp16", bias=bias, use_fast_accum=use_fast_accum
    )
